package com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.jws.soap.SOAPBinding.Style;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebService(wsdlLocation="https://adc-fap0915-crm.oracledemos.com/crmCommonSalesParties/SalesPartyService?WSDL",
  targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/",
  name="SalesPartyService")
@XmlSeeAlso(
  { sdo.commonj.java.ObjectFactory.class, com.oracle.xmlns.apps.crmcommon.assetimport.publicmodel.assetimportservice.ObjectFactory.class, sdo.commonj.ObjectFactory.class, com.oracle.xmlns.apps.cdm.foundation.parties.flex.person.ObjectFactory.class, com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ObjectFactory.class, com.oracle.xmlns.apps.cdm.foundation.parties.organizationservice.ObjectFactory.class, com.oracle.xmlns.apps.cdm.foundation.parties.contactpointservice.ObjectFactory.class, com.oracle.xmlns.apps.cdm.foundation.parties.flex.relationship.ObjectFactory.class, com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.ObjectFactory.class, com.oracle.xmlns.apps.cdm.foundation.parties.flex.contactpoint.ObjectFactory.class, com.oracle.xmlns.apps.cdm.foundation.parties.flex.partysite.ObjectFactory.class, com.oracle.xmlns.apps.cdm.foundation.parties.groupservice.ObjectFactory.class, com.oracle.xmlns.oracleas.schema.oracle_fault_11_0.ObjectFactory.class, com.oracle.xmlns.adf.svc.types.ObjectFactory.class, com.oracle.xmlns.apps.cdm.foundation.parties.flex.organization.ObjectFactory.class, com.oracle.xmlns.apps.cdm.foundation.parties.personservice.ObjectFactory.class, com.oracle.xmlns.apps.cdm.foundation.parties.flex.orgcontact.ObjectFactory.class, com.oracle.xmlns.apps.cdm.foundation.parties.partyservice.ObjectFactory.class, com.oracle.xmlns.apps.cdm.foundation.parties.relationshipservice.ObjectFactory.class, sdo.commonj.xml.ObjectFactory.class, com.oracle.xmlns.apps.cdm.foundation.parties.flex.sourcesystemref.ObjectFactory.class, com.oracle.xmlns.adf.svc.errors.ObjectFactory.class })
@SOAPBinding(style=Style.DOCUMENT, parameterStyle=ParameterStyle.BARE)
public interface SalesPartyService
{
  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/assignSalesAccountChkProfile")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/assignSalesAccountChkProfile", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/assignSalesAccountChkProfile/Fault/ServiceException",
          className=com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/assignSalesAccountChkProfileResponse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    partName="parameters", name="assignSalesAccountChkProfileResponse")
  public com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.AssignSalesAccountChkProfileResponse assignSalesAccountChkProfile(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="assignSalesAccountChkProfile")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.AssignSalesAccountChkProfile parameters)
    throws com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/updateExistingFlag")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/updateExistingFlag", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/updateExistingFlag/Fault/ServiceException",
          className=com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/updateExistingFlagResponse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    partName="parameters", name="updateExistingFlagResponse")
  public com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.UpdateExistingFlagResponse updateExistingFlag(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="updateExistingFlag")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.UpdateExistingFlag parameters)
    throws com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/createOrganizationParty")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/createOrganizationParty", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/createOrganizationParty/Fault/ServiceException",
          className=com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/createOrganizationPartyResponse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    partName="parameters", name="createOrganizationPartyResponse")
  public com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.CreateOrganizationPartyResponse createOrganizationParty(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="createOrganizationParty")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.CreateOrganizationParty parameters)
    throws com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/mergeOrganizationParty")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/mergeOrganizationParty", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/mergeOrganizationParty/Fault/ServiceException",
          className=com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/mergeOrganizationPartyResponse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    partName="parameters", name="mergeOrganizationPartyResponse")
  public com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.MergeOrganizationPartyResponse mergeOrganizationParty(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="mergeOrganizationParty")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.MergeOrganizationParty parameters)
    throws com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/createPersonParty")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/createPersonParty", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/createPersonParty/Fault/ServiceException",
          className=com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/createPersonPartyResponse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    partName="parameters", name="createPersonPartyResponse")
  public com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.CreatePersonPartyResponse createPersonParty(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="createPersonParty")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.CreatePersonParty parameters)
    throws com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/mergePersonParty")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/mergePersonParty", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/mergePersonParty/Fault/ServiceException",
          className=com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/mergePersonPartyResponse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    partName="parameters", name="mergePersonPartyResponse")
  public com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.MergePersonPartyResponse mergePersonParty(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="mergePersonParty")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.MergePersonParty parameters)
    throws com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getSalesAccount")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getSalesAccount", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/getSalesAccount/Fault/ServiceException",
          className=com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/getSalesAccountResponse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    partName="parameters", name="getSalesAccountResponse")
  public com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.GetSalesAccountResponse getSalesAccount(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="getSalesAccount")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.GetSalesAccount parameters)
    throws com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/createSalesAccount")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/createSalesAccount", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/createSalesAccount/Fault/ServiceException",
          className=com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/createSalesAccountResponse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    partName="parameters", name="createSalesAccountResponse")
  public com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.CreateSalesAccountResponse createSalesAccount(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="createSalesAccount")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.CreateSalesAccount parameters)
    throws com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/updateSalesAccount")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/updateSalesAccount", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/updateSalesAccount/Fault/ServiceException",
          className=com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/updateSalesAccountResponse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    partName="parameters", name="updateSalesAccountResponse")
  public com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.UpdateSalesAccountResponse updateSalesAccount(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="updateSalesAccount")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.UpdateSalesAccount parameters)
    throws com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/mergeSalesAccount")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/mergeSalesAccount", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/mergeSalesAccount/Fault/ServiceException",
          className=com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/mergeSalesAccountResponse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    partName="parameters", name="mergeSalesAccountResponse")
  public com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.MergeSalesAccountResponse mergeSalesAccount(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="mergeSalesAccount")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.MergeSalesAccount parameters)
    throws com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findSalesAccount")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findSalesAccount", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/findSalesAccount/Fault/ServiceException",
          className=com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/findSalesAccountResponse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    partName="parameters", name="findSalesAccountResponse")
  public com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.FindSalesAccountResponse findSalesAccount(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="findSalesAccount")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.FindSalesAccount parameters)
    throws com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/createSalesAccountResource")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/createSalesAccountResource", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/createSalesAccountResource/Fault/ServiceException",
          className=com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/createSalesAccountResourceResponse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    partName="parameters", name="createSalesAccountResourceResponse")
  public com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.CreateSalesAccountResourceResponse createSalesAccountResource(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="createSalesAccountResource")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.CreateSalesAccountResource parameters)
    throws com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/updateSalesAccountResource")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/updateSalesAccountResource", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/updateSalesAccountResource/Fault/ServiceException",
          className=com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/updateSalesAccountResourceResponse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    partName="parameters", name="updateSalesAccountResourceResponse")
  public com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.UpdateSalesAccountResourceResponse updateSalesAccountResource(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="updateSalesAccountResource")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.UpdateSalesAccountResource parameters)
    throws com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/deleteSalesAccountResource")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/deleteSalesAccountResource", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/deleteSalesAccountResource/Fault/ServiceException",
          className=com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/deleteSalesAccountResourceResponse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    partName="parameters", name="deleteSalesAccountResourceResponse")
  public com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.DeleteSalesAccountResourceResponse deleteSalesAccountResource(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="deleteSalesAccountResource")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.DeleteSalesAccountResource parameters)
    throws com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findSalesAccountResource")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findSalesAccountResource", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/findSalesAccountResource/Fault/ServiceException",
          className=com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/findSalesAccountResourceResponse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    partName="parameters", name="findSalesAccountResourceResponse")
  public com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.FindSalesAccountResourceResponse findSalesAccountResource(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="findSalesAccountResource")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.FindSalesAccountResource parameters)
    throws com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findSalesAccountResourceAccess")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findSalesAccountResourceAccess", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/findSalesAccountResourceAccess/Fault/ServiceException",
          className=com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/findSalesAccountResourceAccessResponse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    partName="parameters", name="findSalesAccountResourceAccessResponse")
  public com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.FindSalesAccountResourceAccessResponse findSalesAccountResourceAccess(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="findSalesAccountResourceAccess")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.FindSalesAccountResourceAccess parameters)
    throws com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getSalesParty")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getSalesParty", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/getSalesParty/Fault/ServiceException",
          className=com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/getSalesPartyResponse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    partName="parameters", name="getSalesPartyResponse")
  public com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.GetSalesPartyResponse getSalesParty(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="getSalesParty")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.GetSalesParty parameters)
    throws com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/createSalesParty")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/createSalesParty", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/createSalesParty/Fault/ServiceException",
          className=com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/createSalesPartyResponse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    partName="parameters", name="createSalesPartyResponse")
  public com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.CreateSalesPartyResponse createSalesParty(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="createSalesParty")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.CreateSalesParty parameters)
    throws com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/updateSalesParty")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/updateSalesParty", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/updateSalesParty/Fault/ServiceException",
          className=com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/updateSalesPartyResponse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    partName="parameters", name="updateSalesPartyResponse")
  public com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.UpdateSalesPartyResponse updateSalesParty(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="updateSalesParty")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.UpdateSalesParty parameters)
    throws com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findSalesParty")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findSalesParty", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/findSalesParty/Fault/ServiceException",
          className=com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/findSalesPartyResponse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    partName="parameters", name="findSalesPartyResponse")
  public com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.FindSalesPartyResponse findSalesParty(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="findSalesParty")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.FindSalesParty parameters)
    throws com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/updateSalesAccountResourceAsync")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/updateSalesAccountResourceAsync")
  @Oneway
  public void updateSalesAccountResourceAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="updateSalesAccountResourceAsync")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.UpdateSalesAccountResourceAsync parameters);

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findSalesAccountResourceAsync")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findSalesAccountResourceAsync")
  @Oneway
  public void findSalesAccountResourceAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="findSalesAccountResourceAsync")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.FindSalesAccountResourceAsync parameters);

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/createOrganizationPartyAsync")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/createOrganizationPartyAsync")
  @Oneway
  public void createOrganizationPartyAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="createOrganizationPartyAsync")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.CreateOrganizationPartyAsync parameters);

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getSalesPartyAsync")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getSalesPartyAsync")
  @Oneway
  public void getSalesPartyAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="getSalesPartyAsync")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.GetSalesPartyAsync parameters);

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/mergeOrganizationPartyAsync")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/mergeOrganizationPartyAsync")
  @Oneway
  public void mergeOrganizationPartyAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="mergeOrganizationPartyAsync")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.MergeOrganizationPartyAsync parameters);

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/updateExistingFlagAsync")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/updateExistingFlagAsync")
  @Oneway
  public void updateExistingFlagAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="updateExistingFlagAsync")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.UpdateExistingFlagAsync parameters);

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/createSalesAccountResourceAsync")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/createSalesAccountResourceAsync")
  @Oneway
  public void createSalesAccountResourceAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="createSalesAccountResourceAsync")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.CreateSalesAccountResourceAsync parameters);

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findSalesAccountAsync")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findSalesAccountAsync")
  @Oneway
  public void findSalesAccountAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="findSalesAccountAsync")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.FindSalesAccountAsync parameters);

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/mergePersonPartyAsync")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/mergePersonPartyAsync")
  @Oneway
  public void mergePersonPartyAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="mergePersonPartyAsync")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.MergePersonPartyAsync parameters);

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/assignSalesAccountChkProfileAsync")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/assignSalesAccountChkProfileAsync")
  @Oneway
  public void assignSalesAccountChkProfileAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="assignSalesAccountChkProfileAsync")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.AssignSalesAccountChkProfileAsync parameters);

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/createPersonPartyAsync")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/createPersonPartyAsync")
  @Oneway
  public void createPersonPartyAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="createPersonPartyAsync")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.CreatePersonPartyAsync parameters);

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/createSalesAccountAsync")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/createSalesAccountAsync")
  @Oneway
  public void createSalesAccountAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="createSalesAccountAsync")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.CreateSalesAccountAsync parameters);

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/updateSalesAccountAsync")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/updateSalesAccountAsync")
  @Oneway
  public void updateSalesAccountAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="updateSalesAccountAsync")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.UpdateSalesAccountAsync parameters);

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/deleteSalesAccountResourceAsync")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/deleteSalesAccountResourceAsync")
  @Oneway
  public void deleteSalesAccountResourceAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="deleteSalesAccountResourceAsync")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.DeleteSalesAccountResourceAsync parameters);

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/mergeSalesAccountAsync")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/mergeSalesAccountAsync")
  @Oneway
  public void mergeSalesAccountAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="mergeSalesAccountAsync")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.MergeSalesAccountAsync parameters);

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/createSalesPartyAsync")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/createSalesPartyAsync")
  @Oneway
  public void createSalesPartyAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="createSalesPartyAsync")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.CreateSalesPartyAsync parameters);

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/updateSalesPartyAsync")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/updateSalesPartyAsync")
  @Oneway
  public void updateSalesPartyAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="updateSalesPartyAsync")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.UpdateSalesPartyAsync parameters);

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findSalesAccountResourceAccessAsync")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findSalesAccountResourceAccessAsync")
  @Oneway
  public void findSalesAccountResourceAccessAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="findSalesAccountResourceAccessAsync")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.FindSalesAccountResourceAccessAsync parameters);

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findSalesPartyAsync")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findSalesPartyAsync")
  @Oneway
  public void findSalesPartyAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="findSalesPartyAsync")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.FindSalesPartyAsync parameters);

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getSalesAccountAsync")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getSalesAccountAsync")
  @Oneway
  public void getSalesAccountAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="getSalesAccountAsync")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.GetSalesAccountAsync parameters);

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getSalesAccountResource")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getSalesAccountResource", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/getSalesAccountResource/Fault/ServiceException",
          className=com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/getSalesAccountResourceResponse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    partName="parameters", name="getSalesAccountResourceResponse")
  public com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.GetSalesAccountResourceResponse getSalesAccountResource(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="getSalesAccountResource")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.GetSalesAccountResource parameters)
    throws com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getSalesAccountResourceAsync")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getSalesAccountResourceAsync")
  @Oneway
  public void getSalesAccountResourceAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="getSalesAccountResourceAsync")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.GetSalesAccountResourceAsync parameters);

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/createPartyUsage")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/createPartyUsage", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/createPartyUsage/Fault/ServiceException",
          className=com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/createPartyUsageResponse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    partName="parameters", name="createPartyUsageResponse")
  public com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.CreatePartyUsageResponse createPartyUsage(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="createPartyUsage")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.CreatePartyUsage parameters)
    throws com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/createPartyUsageAsync")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/createPartyUsageAsync")
  @Oneway
  public void createPartyUsageAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="createPartyUsageAsync")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.CreatePartyUsageAsync parameters);

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findMySalesAccount")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findMySalesAccount", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/findMySalesAccount/Fault/ServiceException",
          className=com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/findMySalesAccountResponse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    partName="parameters", name="findMySalesAccountResponse")
  public com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.FindMySalesAccountResponse findMySalesAccount(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="findMySalesAccount")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.FindMySalesAccount parameters)
    throws com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findMySalesAccountAsync")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findMySalesAccountAsync")
  @Oneway
  public void findMySalesAccountAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="findMySalesAccountAsync")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.FindMySalesAccountAsync parameters);

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findMySalesAccountMyTeamVC")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findMySalesAccountMyTeamVC", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/findMySalesAccountMyTeamVC/Fault/ServiceException",
          className=com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/findMySalesAccountMyTeamVCResponse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    partName="parameters", name="findMySalesAccountMyTeamVCResponse")
  public com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.FindMySalesAccountMyTeamVCResponse findMySalesAccountMyTeamVC(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="findMySalesAccountMyTeamVC")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.FindMySalesAccountMyTeamVC parameters)
    throws com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findMySalesAccountMyVC")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findMySalesAccountMyVC", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/findMySalesAccountMyVC/Fault/ServiceException",
          className=com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/findMySalesAccountMyVCResponse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    partName="parameters", name="findMySalesAccountMyVCResponse")
  public com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.FindMySalesAccountMyVCResponse findMySalesAccountMyVC(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="findMySalesAccountMyVC")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.FindMySalesAccountMyVC parameters)
    throws com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findMySalesAccountMyVCAsync")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findMySalesAccountMyVCAsync")
  @Oneway
  public void findMySalesAccountMyVCAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="findMySalesAccountMyVCAsync")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.FindMySalesAccountMyVCAsync parameters);

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findMySalesAccountMyTeamVCAsync")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findMySalesAccountMyTeamVCAsync")
  @Oneway
  public void findMySalesAccountMyTeamVCAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="findMySalesAccountMyTeamVCAsync")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.FindMySalesAccountMyTeamVCAsync parameters);

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findSalesAccountMyFavoriteSalesAccountsVC")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findSalesAccountMyFavoriteSalesAccountsVC", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/findSalesAccountMyFavoriteSalesAccountsVC/Fault/ServiceException",
          className=com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/findSalesAccountMyFavoriteSalesAccountsVCResponse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    partName="parameters", name="findSalesAccountMyFavoriteSalesAccountsVCResponse")
  public com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.FindSalesAccountMyFavoriteSalesAccountsVCResponse findSalesAccountMyFavoriteSalesAccountsVC(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="findSalesAccountMyFavoriteSalesAccountsVC")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.FindSalesAccountMyFavoriteSalesAccountsVC parameters)
    throws com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findSalesAccountMyFavoriteSalesAccountsVCAsync")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findSalesAccountMyFavoriteSalesAccountsVCAsync")
  @Oneway
  public void findSalesAccountMyFavoriteSalesAccountsVCAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="findSalesAccountMyFavoriteSalesAccountsVC")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.FindSalesAccountMyFavoriteSalesAccountsVC parameters);

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/deleteSalesParty")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/deleteSalesParty", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/deleteSalesParty/Fault/ServiceException",
          className=com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/deleteSalesPartyResponse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    partName="parameters", name="deleteSalesPartyResponse")
  public com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.DeleteSalesPartyResponse deleteSalesParty(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="deleteSalesParty")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.DeleteSalesParty parameters)
    throws com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/deleteSalesPartyAsync")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/deleteSalesPartyAsync")
  @Oneway
  public void deleteSalesPartyAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="deleteSalesPartyAsync")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.DeleteSalesPartyAsync parameters);

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getDfltObjAttrHints")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getDfltObjAttrHints", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/getDfltObjAttrHints/Fault/ServiceException",
          className=com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/getDfltObjAttrHintsResponse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    partName="parameters", name="getDfltObjAttrHintsResponse")
  public com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.GetDfltObjAttrHintsResponse getDfltObjAttrHints(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="getDfltObjAttrHints")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.GetDfltObjAttrHints parameters)
    throws com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getServiceLastUpdateTime")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getServiceLastUpdateTime", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/getServiceLastUpdateTime/Fault/ServiceException",
          className=com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/getServiceLastUpdateTimeResponse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    partName="parameters", name="getServiceLastUpdateTimeResponse")
  public com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.GetServiceLastUpdateTimeResponse getServiceLastUpdateTime(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="getServiceLastUpdateTime")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.GetServiceLastUpdateTime parameters)
    throws com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getEntityList")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getEntityList", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/getEntityList/Fault/ServiceException",
          className=com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesPartyService/getEntityListResponse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    partName="parameters", name="getEntityListResponse")
  public com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.GetEntityListResponse getEntityList(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="getEntityList")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.GetEntityList parameters)
    throws com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getDfltObjAttrHintsAsync")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getDfltObjAttrHintsAsync")
  @Oneway
  public void getDfltObjAttrHintsAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="getDfltObjAttrHintsAsync")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.GetDfltObjAttrHintsAsync parameters);

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getEntityListAsync")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getEntityListAsync")
  @Oneway
  public void getEntityListAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="getEntityListAsync")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.GetEntityListAsync parameters);

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getServiceLastUpdateTimeAsync")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getServiceLastUpdateTimeAsync")
  @Oneway
  public void getServiceLastUpdateTimeAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      partName="parameters", name="getServiceLastUpdateTimeAsync")
    com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.types.GetServiceLastUpdateTimeAsync parameters);
}
