package com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebServiceClient(wsdlLocation="https://adc-fap0915-crm.oracledemos.com/crmCommonSalesParties/SalesPartyService?WSDL",
  targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/",
  name="SalesPartyService")
public class SalesPartyService_Service
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.SalesPartyService_Service");
      URL baseUrl = SalesPartyService_Service.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            SalesPartyService_Service.class.getResource("https://adc-fap0915-crm.oracledemos.com/crmCommonSalesParties/SalesPartyService?WSDL");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "https://adc-fap0915-crm.oracledemos.com/crmCommonSalesParties/SalesPartyService?WSDL");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "https://adc-fap0915-crm.oracledemos.com/crmCommonSalesParties/SalesPartyService?WSDL");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using https://adc-fap0915-crm.oracledemos.com/crmCommonSalesParties/SalesPartyService?WSDL",
          e);
    }
  }

  public SalesPartyService_Service()
  {
    super(wsdlLocationURL,
          new QName("http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/",
                    "SalesPartyService"));
  }

  public SalesPartyService_Service(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="SalesPartyServiceSoapHttpPort")
  public com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.SalesPartyService getSalesPartyServiceSoapHttpPort()
  {
    return (com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.SalesPartyService) super.getPort(new QName("http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/",
                                                                                                                        "SalesPartyServiceSoapHttpPort"),
                                                                                                              com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.SalesPartyService.class);
  }

  @WebEndpoint(name="SalesPartyServiceSoapHttpPort")
  public com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.SalesPartyService getSalesPartyServiceSoapHttpPort(WebServiceFeature... features)
  {
    return (com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.SalesPartyService) super.getPort(new QName("http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/",
                                                                                                                        "SalesPartyServiceSoapHttpPort"),
                                                                                                              com.oracle.xmlns.apps.crmcommon.salesparties.salespartiesservice.SalesPartyService.class,
                                                                                                              features);
  }
}
