package salesaccount;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebServiceClient(wsdlLocation="https://adc-fap0915-crm.oracledemos.com/crmCommonSalesParties/SalesAccountsService?WSDL",
  targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/",
  name="SalesAccountsService")
public class SalesAccountsService_Service
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("salesaccount.SalesAccountsService_Service");
      URL baseUrl = SalesAccountsService_Service.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            SalesAccountsService_Service.class.getResource("https://adc-fap0915-crm.oracledemos.com/crmCommonSalesParties/SalesAccountsService?WSDL");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "https://adc-fap0915-crm.oracledemos.com/crmCommonSalesParties/SalesAccountsService?WSDL");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "https://adc-fap0915-crm.oracledemos.com/crmCommonSalesParties/SalesAccountsService?WSDL");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using https://adc-fap0915-crm.oracledemos.com/crmCommonSalesParties/SalesAccountsService?WSDL",
          e);
    }
  }

  public SalesAccountsService_Service()
  {
    super(wsdlLocationURL,
          new QName("http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/",
                    "SalesAccountsService"));
  }

  public SalesAccountsService_Service(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="SalesAccountsServiceSoapHttpPort")
  public salesaccount.SalesAccountsService getSalesAccountsServiceSoapHttpPort()
  {
    return (salesaccount.SalesAccountsService) super.getPort(new QName("http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/",
                                                                       "SalesAccountsServiceSoapHttpPort"),
                                                             salesaccount.SalesAccountsService.class);
  }

  @WebEndpoint(name="SalesAccountsServiceSoapHttpPort")
  public salesaccount.SalesAccountsService getSalesAccountsServiceSoapHttpPort(WebServiceFeature... features)
  {
    return (salesaccount.SalesAccountsService) super.getPort(new QName("http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/",
                                                                       "SalesAccountsServiceSoapHttpPort"),
                                                             salesaccount.SalesAccountsService.class,
                                                             features);
  }
}
