package salesaccount;

import java.util.List;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebService(wsdlLocation="https://adc-fap0915-crm.oracledemos.com/crmCommonSalesParties/SalesAccountsService?WSDL",
  targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/",
  name="SalesAccountsService")
@XmlSeeAlso(
  { salesaccount.types.ObjectFactory.class })
public interface SalesAccountsService
{
  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getSalesAccount")
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getSalesAccount", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesAccountsService/getSalesAccount/Fault/ServiceException",
          className=salesaccount.ServiceException.class) }, output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesAccountsService/getSalesAccountResponse")
  @ResponseWrapper(localName="getSalesAccountResponse", targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.GetSalesAccountResponse")
  @RequestWrapper(localName="getSalesAccount", targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.GetSalesAccount")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    name="result")
  public salesaccount.types.SalesAccount getSalesAccount(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="salesAccountId")
    long salesAccountId)
    throws salesaccount.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/createSalesAccount")
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/createSalesAccount", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesAccountsService/createSalesAccount/Fault/ServiceException",
          className=salesaccount.ServiceException.class) }, output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesAccountsService/createSalesAccountResponse")
  @ResponseWrapper(localName="createSalesAccountResponse",
    targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.CreateSalesAccountResponse")
  @RequestWrapper(localName="createSalesAccount", targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.CreateSalesAccount")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    name="result")
  public salesaccount.types.SalesAccount createSalesAccount(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="salesAccount")
    salesaccount.types.SalesAccount salesAccount)
    throws salesaccount.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/updateSalesAccount")
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/updateSalesAccount", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesAccountsService/updateSalesAccount/Fault/ServiceException",
          className=salesaccount.ServiceException.class) }, output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesAccountsService/updateSalesAccountResponse")
  @ResponseWrapper(localName="updateSalesAccountResponse",
    targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.UpdateSalesAccountResponse")
  @RequestWrapper(localName="updateSalesAccount", targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.UpdateSalesAccount")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    name="result")
  public salesaccount.types.SalesAccount updateSalesAccount(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="salesAccount")
    salesaccount.types.SalesAccount salesAccount)
    throws salesaccount.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/mergeSalesAccount")
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/mergeSalesAccount", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesAccountsService/mergeSalesAccount/Fault/ServiceException",
          className=salesaccount.ServiceException.class) }, output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesAccountsService/mergeSalesAccountResponse")
  @ResponseWrapper(localName="mergeSalesAccountResponse", targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.MergeSalesAccountResponse")
  @RequestWrapper(localName="mergeSalesAccount", targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.MergeSalesAccount")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    name="result")
  public salesaccount.types.SalesAccount mergeSalesAccount(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="salesAccount")
    salesaccount.types.SalesAccount salesAccount)
    throws salesaccount.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findSalesAccount")
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findSalesAccount", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesAccountsService/findSalesAccount/Fault/ServiceException",
          className=salesaccount.ServiceException.class) }, output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesAccountsService/findSalesAccountResponse")
  @ResponseWrapper(localName="findSalesAccountResponse", targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.FindSalesAccountResponse")
  @RequestWrapper(localName="findSalesAccount", targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.FindSalesAccount")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    name="result")
  public List<salesaccount.types.SalesAccount> findSalesAccount(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="findCriteria")
    salesaccount.types.FindCriteria findCriteria,
    @WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="findControl")
    salesaccount.types.FindControl findControl)
    throws salesaccount.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getSalesAccountTerritory")
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getSalesAccountTerritory", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesAccountsService/getSalesAccountTerritory/Fault/ServiceException",
          className=salesaccount.ServiceException.class) }, output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesAccountsService/getSalesAccountTerritoryResponse")
  @ResponseWrapper(localName="getSalesAccountTerritoryResponse",
    targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.GetSalesAccountTerritoryResponse")
  @RequestWrapper(localName="getSalesAccountTerritory", targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.GetSalesAccountTerritory")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    name="result")
  public salesaccount.types.SalesAccountTerritory getSalesAccountTerritory(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="sAccountTerritoryId")
    long sAccountTerritoryId)
    throws salesaccount.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/createSalesAccountTerritory")
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/createSalesAccountTerritory", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesAccountsService/createSalesAccountTerritory/Fault/ServiceException",
          className=salesaccount.ServiceException.class) }, output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesAccountsService/createSalesAccountTerritoryResponse")
  @ResponseWrapper(localName="createSalesAccountTerritoryResponse",
    targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.CreateSalesAccountTerritoryResponse")
  @RequestWrapper(localName="createSalesAccountTerritory",
    targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.CreateSalesAccountTerritory")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    name="result")
  public salesaccount.types.SalesAccountTerritory createSalesAccountTerritory(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="salesAccountTerritory")
    salesaccount.types.SalesAccountTerritory salesAccountTerritory)
    throws salesaccount.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/updateSalesAccountTerritory")
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/updateSalesAccountTerritory", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesAccountsService/updateSalesAccountTerritory/Fault/ServiceException",
          className=salesaccount.ServiceException.class) }, output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesAccountsService/updateSalesAccountTerritoryResponse")
  @ResponseWrapper(localName="updateSalesAccountTerritoryResponse",
    targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.UpdateSalesAccountTerritoryResponse")
  @RequestWrapper(localName="updateSalesAccountTerritory",
    targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.UpdateSalesAccountTerritory")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    name="result")
  public salesaccount.types.SalesAccountTerritory updateSalesAccountTerritory(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="salesAccountTerritory")
    salesaccount.types.SalesAccountTerritory salesAccountTerritory)
    throws salesaccount.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/deleteSalesAccountTerritory")
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/deleteSalesAccountTerritory", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesAccountsService/deleteSalesAccountTerritory/Fault/ServiceException",
          className=salesaccount.ServiceException.class) }, output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesAccountsService/deleteSalesAccountTerritoryResponse")
  @ResponseWrapper(localName="deleteSalesAccountTerritoryResponse",
    targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.DeleteSalesAccountTerritoryResponse")
  @RequestWrapper(localName="deleteSalesAccountTerritory",
    targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.DeleteSalesAccountTerritory")
  public void deleteSalesAccountTerritory(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="salesAccountTerritory")
    salesaccount.types.SalesAccountTerritory salesAccountTerritory)
    throws salesaccount.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/mergeSalesAccountTerritory")
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/mergeSalesAccountTerritory", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesAccountsService/mergeSalesAccountTerritory/Fault/ServiceException",
          className=salesaccount.ServiceException.class) }, output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesAccountsService/mergeSalesAccountTerritoryResponse")
  @ResponseWrapper(localName="mergeSalesAccountTerritoryResponse",
    targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.MergeSalesAccountTerritoryResponse")
  @RequestWrapper(localName="mergeSalesAccountTerritory", targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.MergeSalesAccountTerritory")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    name="result")
  public salesaccount.types.SalesAccountTerritory mergeSalesAccountTerritory(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="salesAccountTerritory")
    salesaccount.types.SalesAccountTerritory salesAccountTerritory)
    throws salesaccount.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findSalesAccountTerritory")
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findSalesAccountTerritory", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesAccountsService/findSalesAccountTerritory/Fault/ServiceException",
          className=salesaccount.ServiceException.class) }, output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesAccountsService/findSalesAccountTerritoryResponse")
  @ResponseWrapper(localName="findSalesAccountTerritoryResponse",
    targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.FindSalesAccountTerritoryResponse")
  @RequestWrapper(localName="findSalesAccountTerritory", targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.FindSalesAccountTerritory")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    name="result")
  public List<salesaccount.types.SalesAccountTerritory> findSalesAccountTerritory(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="findCriteria")
    salesaccount.types.FindCriteria findCriteria,
    @WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="findControl")
    salesaccount.types.FindControl findControl)
    throws salesaccount.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getSalesAccountContacts")
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getSalesAccountContacts", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesAccountsService/getSalesAccountContacts/Fault/ServiceException",
          className=salesaccount.ServiceException.class) }, output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesAccountsService/getSalesAccountContactsResponse")
  @ResponseWrapper(localName="getSalesAccountContactsResponse",
    targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.GetSalesAccountContactsResponse")
  @RequestWrapper(localName="getSalesAccountContacts", targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.GetSalesAccountContacts")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    name="result")
  public salesaccount.types.SalesAccountContacts getSalesAccountContacts(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="sAccountContactId")
    long sAccountContactId)
    throws salesaccount.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/createSalesAccountContacts")
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/createSalesAccountContacts", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesAccountsService/createSalesAccountContacts/Fault/ServiceException",
          className=salesaccount.ServiceException.class) }, output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesAccountsService/createSalesAccountContactsResponse")
  @ResponseWrapper(localName="createSalesAccountContactsResponse",
    targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.CreateSalesAccountContactsResponse")
  @RequestWrapper(localName="createSalesAccountContacts", targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.CreateSalesAccountContacts")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    name="result")
  public salesaccount.types.SalesAccountContacts createSalesAccountContacts(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="salesAccountContacts")
    salesaccount.types.SalesAccountContacts salesAccountContacts)
    throws salesaccount.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/updateSalesAccountContacts")
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/updateSalesAccountContacts", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesAccountsService/updateSalesAccountContacts/Fault/ServiceException",
          className=salesaccount.ServiceException.class) }, output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesAccountsService/updateSalesAccountContactsResponse")
  @ResponseWrapper(localName="updateSalesAccountContactsResponse",
    targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.UpdateSalesAccountContactsResponse")
  @RequestWrapper(localName="updateSalesAccountContacts", targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.UpdateSalesAccountContacts")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    name="result")
  public salesaccount.types.SalesAccountContacts updateSalesAccountContacts(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="salesAccountContacts")
    salesaccount.types.SalesAccountContacts salesAccountContacts)
    throws salesaccount.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/deleteSalesAccountContacts")
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/deleteSalesAccountContacts", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesAccountsService/deleteSalesAccountContacts/Fault/ServiceException",
          className=salesaccount.ServiceException.class) }, output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesAccountsService/deleteSalesAccountContactsResponse")
  @ResponseWrapper(localName="deleteSalesAccountContactsResponse",
    targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.DeleteSalesAccountContactsResponse")
  @RequestWrapper(localName="deleteSalesAccountContacts", targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.DeleteSalesAccountContacts")
  public void deleteSalesAccountContacts(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="salesAccountContacts")
    salesaccount.types.SalesAccountContacts salesAccountContacts)
    throws salesaccount.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/mergeSalesAccountContacts")
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/mergeSalesAccountContacts", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesAccountsService/mergeSalesAccountContacts/Fault/ServiceException",
          className=salesaccount.ServiceException.class) }, output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesAccountsService/mergeSalesAccountContactsResponse")
  @ResponseWrapper(localName="mergeSalesAccountContactsResponse",
    targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.MergeSalesAccountContactsResponse")
  @RequestWrapper(localName="mergeSalesAccountContacts", targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.MergeSalesAccountContacts")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    name="result")
  public salesaccount.types.SalesAccountContacts mergeSalesAccountContacts(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="salesAccountContacts")
    salesaccount.types.SalesAccountContacts salesAccountContacts)
    throws salesaccount.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findSalesAccountContacts")
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findSalesAccountContacts", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesAccountsService/findSalesAccountContacts/Fault/ServiceException",
          className=salesaccount.ServiceException.class) }, output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesAccountsService/findSalesAccountContactsResponse")
  @ResponseWrapper(localName="findSalesAccountContactsResponse",
    targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.FindSalesAccountContactsResponse")
  @RequestWrapper(localName="findSalesAccountContacts", targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.FindSalesAccountContacts")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    name="result")
  public List<salesaccount.types.SalesAccountContacts> findSalesAccountContacts(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="findCriteria")
    salesaccount.types.FindCriteria findCriteria,
    @WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="findControl")
    salesaccount.types.FindControl findControl)
    throws salesaccount.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/updateSalesAccountTerritoryAsync")
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/updateSalesAccountTerritoryAsync")
  @RequestWrapper(localName="updateSalesAccountTerritoryAsync",
    targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.UpdateSalesAccountTerritoryAsync")
  @Oneway
  public void updateSalesAccountTerritoryAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="salesAccountTerritory")
    salesaccount.types.SalesAccountTerritory salesAccountTerritory);

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/createSalesAccountAsync")
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/createSalesAccountAsync")
  @RequestWrapper(localName="createSalesAccountAsync", targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.CreateSalesAccountAsync")
  @Oneway
  public void createSalesAccountAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="salesAccount")
    salesaccount.types.SalesAccount salesAccount);

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/updateSalesAccountAsync")
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/updateSalesAccountAsync")
  @RequestWrapper(localName="updateSalesAccountAsync", targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.UpdateSalesAccountAsync")
  @Oneway
  public void updateSalesAccountAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="salesAccount")
    salesaccount.types.SalesAccount salesAccount);

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/deleteSalesAccountContactsAsync")
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/deleteSalesAccountContactsAsync")
  @RequestWrapper(localName="deleteSalesAccountContactsAsync",
    targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.DeleteSalesAccountContactsAsync")
  @Oneway
  public void deleteSalesAccountContactsAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="salesAccountContacts")
    salesaccount.types.SalesAccountContacts salesAccountContacts);

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findSalesAccountTerritoryAsync")
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findSalesAccountTerritoryAsync")
  @RequestWrapper(localName="findSalesAccountTerritoryAsync",
    targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.FindSalesAccountTerritoryAsync")
  @Oneway
  public void findSalesAccountTerritoryAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="findCriteria")
    salesaccount.types.FindCriteria findCriteria,
    @WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="findControl")
    salesaccount.types.FindControl findControl);

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getSalesAccountContactsAsync")
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getSalesAccountContactsAsync")
  @RequestWrapper(localName="getSalesAccountContactsAsync",
    targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.GetSalesAccountContactsAsync")
  @Oneway
  public void getSalesAccountContactsAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="sAccountContactId")
    long sAccountContactId);

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/mergeSalesAccountAsync")
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/mergeSalesAccountAsync")
  @RequestWrapper(localName="mergeSalesAccountAsync", targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.MergeSalesAccountAsync")
  @Oneway
  public void mergeSalesAccountAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="salesAccount")
    salesaccount.types.SalesAccount salesAccount);

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/mergeSalesAccountTerritoryAsync")
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/mergeSalesAccountTerritoryAsync")
  @RequestWrapper(localName="mergeSalesAccountTerritoryAsync",
    targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.MergeSalesAccountTerritoryAsync")
  @Oneway
  public void mergeSalesAccountTerritoryAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="salesAccountTerritory")
    salesaccount.types.SalesAccountTerritory salesAccountTerritory);

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getSalesAccountTerritoryAsync")
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getSalesAccountTerritoryAsync")
  @RequestWrapper(localName="getSalesAccountTerritoryAsync",
    targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.GetSalesAccountTerritoryAsync")
  @Oneway
  public void getSalesAccountTerritoryAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="sAccountTerritoryId")
    long sAccountTerritoryId);

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/mergeSalesAccountContactsAsync")
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/mergeSalesAccountContactsAsync")
  @RequestWrapper(localName="mergeSalesAccountContactsAsync",
    targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.MergeSalesAccountContactsAsync")
  @Oneway
  public void mergeSalesAccountContactsAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="salesAccountContacts")
    salesaccount.types.SalesAccountContacts salesAccountContacts);

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/createSalesAccountTerritoryAsync")
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/createSalesAccountTerritoryAsync")
  @RequestWrapper(localName="createSalesAccountTerritoryAsync",
    targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.CreateSalesAccountTerritoryAsync")
  @Oneway
  public void createSalesAccountTerritoryAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="salesAccountTerritory")
    salesaccount.types.SalesAccountTerritory salesAccountTerritory);

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/createSalesAccountContactsAsync")
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/createSalesAccountContactsAsync")
  @RequestWrapper(localName="createSalesAccountContactsAsync",
    targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.CreateSalesAccountContactsAsync")
  @Oneway
  public void createSalesAccountContactsAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="salesAccountContacts")
    salesaccount.types.SalesAccountContacts salesAccountContacts);

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/deleteSalesAccountTerritoryAsync")
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/deleteSalesAccountTerritoryAsync")
  @RequestWrapper(localName="deleteSalesAccountTerritoryAsync",
    targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.DeleteSalesAccountTerritoryAsync")
  @Oneway
  public void deleteSalesAccountTerritoryAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="salesAccountTerritory")
    salesaccount.types.SalesAccountTerritory salesAccountTerritory);

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findSalesAccountContactsAsync")
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findSalesAccountContactsAsync")
  @RequestWrapper(localName="findSalesAccountContactsAsync",
    targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.FindSalesAccountContactsAsync")
  @Oneway
  public void findSalesAccountContactsAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="findCriteria")
    salesaccount.types.FindCriteria findCriteria,
    @WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="findControl")
    salesaccount.types.FindControl findControl);

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/updateSalesAccountContactsAsync")
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/updateSalesAccountContactsAsync")
  @RequestWrapper(localName="updateSalesAccountContactsAsync",
    targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.UpdateSalesAccountContactsAsync")
  @Oneway
  public void updateSalesAccountContactsAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="salesAccountContacts")
    salesaccount.types.SalesAccountContacts salesAccountContacts);

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getSalesAccountAsync")
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getSalesAccountAsync")
  @RequestWrapper(localName="getSalesAccountAsync", targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.GetSalesAccountAsync")
  @Oneway
  public void getSalesAccountAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="salesAccountId")
    long salesAccountId);

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findSalesAccountAsync")
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findSalesAccountAsync")
  @RequestWrapper(localName="findSalesAccountAsync", targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.FindSalesAccountAsync")
  @Oneway
  public void findSalesAccountAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="findCriteria")
    salesaccount.types.FindCriteria findCriteria,
    @WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="findControl")
    salesaccount.types.FindControl findControl);

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/deleteSalesAccount")
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/deleteSalesAccount", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesAccountsService/deleteSalesAccount/Fault/ServiceException",
          className=salesaccount.ServiceException.class) }, output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesAccountsService/deleteSalesAccountResponse")
  @ResponseWrapper(localName="deleteSalesAccountResponse",
    targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.DeleteSalesAccountResponse")
  @RequestWrapper(localName="deleteSalesAccount", targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.DeleteSalesAccount")
  public void deleteSalesAccount(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="salesAccount")
    salesaccount.types.SalesAccount salesAccount)
    throws salesaccount.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/deleteSalesAccountAsync")
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/deleteSalesAccountAsync")
  @RequestWrapper(localName="deleteSalesAccountAsync", targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.DeleteSalesAccountAsync")
  @Oneway
  public void deleteSalesAccountAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="salesAccount")
    salesaccount.types.SalesAccount salesAccount);

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getSalesAccountContactPoints")
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getSalesAccountContactPoints", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesAccountsService/getSalesAccountContactPoints/Fault/ServiceException",
          className=salesaccount.ServiceException.class) }, output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesAccountsService/getSalesAccountContactPointsResponse")
  @ResponseWrapper(localName="getSalesAccountContactPointsResponse",
    targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.GetSalesAccountContactPointsResponse")
  @RequestWrapper(localName="getSalesAccountContactPoints",
    targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.GetSalesAccountContactPoints")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    name="result")
  public salesaccount.types.SalesAccountContactPoints getSalesAccountContactPoints(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="sAccountContactPointId")
    long sAccountContactPointId)
    throws salesaccount.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/createSalesAccountContactPoints")
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/createSalesAccountContactPoints", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesAccountsService/createSalesAccountContactPoints/Fault/ServiceException",
          className=salesaccount.ServiceException.class) }, output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesAccountsService/createSalesAccountContactPointsResponse")
  @ResponseWrapper(localName="createSalesAccountContactPointsResponse",
    targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.CreateSalesAccountContactPointsResponse")
  @RequestWrapper(localName="createSalesAccountContactPoints",
    targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.CreateSalesAccountContactPoints")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    name="result")
  public salesaccount.types.SalesAccountContactPoints createSalesAccountContactPoints(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="salesAccountContactPoints")
    salesaccount.types.SalesAccountContactPoints salesAccountContactPoints)
    throws salesaccount.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/updateSalesAccountContactPoints")
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/updateSalesAccountContactPoints", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesAccountsService/updateSalesAccountContactPoints/Fault/ServiceException",
          className=salesaccount.ServiceException.class) }, output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesAccountsService/updateSalesAccountContactPointsResponse")
  @ResponseWrapper(localName="updateSalesAccountContactPointsResponse",
    targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.UpdateSalesAccountContactPointsResponse")
  @RequestWrapper(localName="updateSalesAccountContactPoints",
    targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.UpdateSalesAccountContactPoints")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    name="result")
  public salesaccount.types.SalesAccountContactPoints updateSalesAccountContactPoints(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="salesAccountContactPoints")
    salesaccount.types.SalesAccountContactPoints salesAccountContactPoints)
    throws salesaccount.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/deleteSalesAccountContactPoints")
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/deleteSalesAccountContactPoints", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesAccountsService/deleteSalesAccountContactPoints/Fault/ServiceException",
          className=salesaccount.ServiceException.class) }, output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesAccountsService/deleteSalesAccountContactPointsResponse")
  @ResponseWrapper(localName="deleteSalesAccountContactPointsResponse",
    targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.DeleteSalesAccountContactPointsResponse")
  @RequestWrapper(localName="deleteSalesAccountContactPoints",
    targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.DeleteSalesAccountContactPoints")
  public void deleteSalesAccountContactPoints(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="salesAccountContactPoints")
    salesaccount.types.SalesAccountContactPoints salesAccountContactPoints)
    throws salesaccount.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/mergeSalesAccountContactPoints")
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/mergeSalesAccountContactPoints", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesAccountsService/mergeSalesAccountContactPoints/Fault/ServiceException",
          className=salesaccount.ServiceException.class) }, output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesAccountsService/mergeSalesAccountContactPointsResponse")
  @ResponseWrapper(localName="mergeSalesAccountContactPointsResponse",
    targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.MergeSalesAccountContactPointsResponse")
  @RequestWrapper(localName="mergeSalesAccountContactPoints",
    targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.MergeSalesAccountContactPoints")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    name="result")
  public salesaccount.types.SalesAccountContactPoints mergeSalesAccountContactPoints(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="salesAccountContactPoints")
    salesaccount.types.SalesAccountContactPoints salesAccountContactPoints)
    throws salesaccount.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findSalesAccountContactPoints")
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findSalesAccountContactPoints", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesAccountsService/findSalesAccountContactPoints/Fault/ServiceException",
          className=salesaccount.ServiceException.class) }, output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesAccountsService/findSalesAccountContactPointsResponse")
  @ResponseWrapper(localName="findSalesAccountContactPointsResponse",
    targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.FindSalesAccountContactPointsResponse")
  @RequestWrapper(localName="findSalesAccountContactPoints",
    targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.FindSalesAccountContactPoints")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    name="result")
  public List<salesaccount.types.SalesAccountContactPoints> findSalesAccountContactPoints(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="findCriteria")
    salesaccount.types.FindCriteria findCriteria,
    @WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="findControl")
    salesaccount.types.FindControl findControl)
    throws salesaccount.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/updateSalesAccountContactPointsAsync")
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/updateSalesAccountContactPointsAsync")
  @RequestWrapper(localName="updateSalesAccountContactPointsAsync",
    targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.UpdateSalesAccountContactPointsAsync")
  @Oneway
  public void updateSalesAccountContactPointsAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="salesAccountContactPoints")
    salesaccount.types.SalesAccountContactPoints salesAccountContactPoints);

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/mergeSalesAccountContactPointsAsync")
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/mergeSalesAccountContactPointsAsync")
  @RequestWrapper(localName="mergeSalesAccountContactPointsAsync",
    targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.MergeSalesAccountContactPointsAsync")
  @Oneway
  public void mergeSalesAccountContactPointsAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="salesAccountContactPoints")
    salesaccount.types.SalesAccountContactPoints salesAccountContactPoints);

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getSalesAccountContactPointsAsync")
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getSalesAccountContactPointsAsync")
  @RequestWrapper(localName="getSalesAccountContactPointsAsync",
    targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.GetSalesAccountContactPointsAsync")
  @Oneway
  public void getSalesAccountContactPointsAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="sAccountContactPointId")
    long sAccountContactPointId);

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/deleteSalesAccountContactPointsAsync")
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/deleteSalesAccountContactPointsAsync")
  @RequestWrapper(localName="deleteSalesAccountContactPointsAsync",
    targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.DeleteSalesAccountContactPointsAsync")
  @Oneway
  public void deleteSalesAccountContactPointsAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="salesAccountContactPoints")
    salesaccount.types.SalesAccountContactPoints salesAccountContactPoints);

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findSalesAccountContactPointsAsync")
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findSalesAccountContactPointsAsync")
  @RequestWrapper(localName="findSalesAccountContactPointsAsync",
    targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.FindSalesAccountContactPointsAsync")
  @Oneway
  public void findSalesAccountContactPointsAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="findCriteria")
    salesaccount.types.FindCriteria findCriteria,
    @WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="findControl")
    salesaccount.types.FindControl findControl);

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/createSalesAccountContactPointsAsync")
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/createSalesAccountContactPointsAsync")
  @RequestWrapper(localName="createSalesAccountContactPointsAsync",
    targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.CreateSalesAccountContactPointsAsync")
  @Oneway
  public void createSalesAccountContactPointsAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="salesAccountContactPoints")
    salesaccount.types.SalesAccountContactPoints salesAccountContactPoints);

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findAccountsOfParty")
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findAccountsOfParty", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesAccountsService/findAccountsOfParty/Fault/ServiceException",
          className=salesaccount.ServiceException.class) }, output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesAccountsService/findAccountsOfPartyResponse")
  @ResponseWrapper(localName="findAccountsOfPartyResponse",
    targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.FindAccountsOfPartyResponse")
  @RequestWrapper(localName="findAccountsOfParty", targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.FindAccountsOfParty")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    name="result")
  public List<salesaccount.types.SalesAccount> findAccountsOfParty(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="findCriteria")
    salesaccount.types.FindCriteria findCriteria,
    @WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="BindPartyId")
    long bindPartyId, @WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="findControl")
    salesaccount.types.FindControl findControl)
    throws salesaccount.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findAccountsOfPartyAsync")
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findAccountsOfPartyAsync")
  @RequestWrapper(localName="findAccountsOfPartyAsync", targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.FindAccountsOfPartyAsync")
  @Oneway
  public void findAccountsOfPartyAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="findCriteria")
    salesaccount.types.FindCriteria findCriteria,
    @WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="BindPartyId")
    long bindPartyId, @WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="findControl")
    salesaccount.types.FindControl findControl);

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getDfltObjAttrHints")
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getDfltObjAttrHints", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesAccountsService/getDfltObjAttrHints/Fault/ServiceException",
          className=salesaccount.ServiceException.class) }, output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesAccountsService/getDfltObjAttrHintsResponse")
  @ResponseWrapper(localName="getDfltObjAttrHintsResponse",
    targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.GetDfltObjAttrHintsResponse")
  @RequestWrapper(localName="getDfltObjAttrHints", targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.GetDfltObjAttrHints")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    name="result")
  public salesaccount.types.ObjAttrHints getDfltObjAttrHints(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="viewName")
    String viewName, @WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="localeName")
    String localeName)
    throws salesaccount.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getServiceLastUpdateTime")
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getServiceLastUpdateTime", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesAccountsService/getServiceLastUpdateTime/Fault/ServiceException",
          className=salesaccount.ServiceException.class) }, output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesAccountsService/getServiceLastUpdateTimeResponse")
  @ResponseWrapper(localName="getServiceLastUpdateTimeResponse",
    targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.GetServiceLastUpdateTimeResponse")
  @RequestWrapper(localName="getServiceLastUpdateTime", targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.GetServiceLastUpdateTime")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    name="result")
  public XMLGregorianCalendar getServiceLastUpdateTime()
    throws salesaccount.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getEntityList")
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getEntityList", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesAccountsService/getEntityList/Fault/ServiceException",
          className=salesaccount.ServiceException.class) }, output="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/SalesAccountsService/getEntityListResponse")
  @ResponseWrapper(localName="getEntityListResponse", targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.GetEntityListResponse")
  @RequestWrapper(localName="getEntityList", targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.GetEntityList")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    name="result")
  public List<salesaccount.types.ServiceViewInfo> getEntityList()
    throws salesaccount.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getDfltObjAttrHintsAsync")
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getDfltObjAttrHintsAsync")
  @RequestWrapper(localName="getDfltObjAttrHintsAsync", targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.GetDfltObjAttrHintsAsync")
  @Oneway
  public void getDfltObjAttrHintsAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="viewName")
    String viewName, @WebParam(targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
      name="localeName")
    String localeName);

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getEntityListAsync")
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getEntityListAsync")
  @RequestWrapper(localName="getEntityListAsync", targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.GetEntityListAsync")
  @Oneway
  public void getEntityListAsync();

  @WebMethod(action="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getServiceLastUpdateTimeAsync")
  @Action(input="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getServiceLastUpdateTimeAsync")
  @RequestWrapper(localName="getServiceLastUpdateTimeAsync",
    targetNamespace="http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/",
    className="salesaccount.types.GetServiceLastUpdateTimeAsync")
  @Oneway
  public void getServiceLastUpdateTimeAsync();
}
